
//! Autogenerated weights for `pallet_assignment`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-22, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `sachinc-U-20`, CPU: `11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_assignment
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/assignment/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn add_employee(i: u32, ) -> Weight;
    fn update_employee(i: u32, ) -> Weight;
    fn remove_employee(_i: u32, ) -> Weight;
}

/// Weight functions for `pallet_assignment`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Assignment Employees (r:1 w:1)
	/// The range of component `i` is `[1, 100]`.
	fn add_employee(i: u32, ) -> Weight {
		// Minimum execution time: 21_041 nanoseconds.
		Weight::from_ref_time(23_686_645_u64)
			// Standard Error: 939
			.saturating_add(Weight::from_ref_time(7_142_u64).saturating_mul(i as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: Assignment Employees (r:1 w:1)
	/// The range of component `i` is `[1, 100]`.
	fn update_employee(i: u32, ) -> Weight {
		// Minimum execution time: 24_155 nanoseconds.
		Weight::from_ref_time(27_159_715_u64)
			// Standard Error: 1_779
			.saturating_add(Weight::from_ref_time(2_318_u64).saturating_mul(i as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: Assignment Employees (r:0 w:1)
	/// The range of component `i` is `[1, 100]`.
	fn remove_employee(_i: u32, ) -> Weight {
		// Minimum execution time: 16_740 nanoseconds.
		Weight::from_ref_time(19_164_891_u64)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
